name: publish 

on:
  push:
    branches: [ "main" ]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!
        
      - name: 'qr_plus'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.PUB_CREDENTIAL }}
          skipTests: true
          format: false
          dryRunOnly: false
          flutter: true
          force: true
